version: '3.8'
services:
  streamlitapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: streamlitapp
    ports:
      - "8501:8501"
    command: [
      "streamlit", "run", "example.py",
      "--server.port=8501",
      "--server.address=0.0.0.0",
    ]
